### PR TITLE
Added timeline component and it's configuration

### PR DESCRIPTION
**Pull request by Asya404**
- Added story-timeline component.
- Implemented props to configure timeline content dynamically.

### CODE REVIEW

**Comment by yyx990805** [comment]
this is how it looks
image

could we add a white background to the container with timeline entries? (here's the original component presentation https://www.lightningdesignsystem.com/components/activity-timeline/)

**Comment by Asya404** [comment]
@yyx990805 I simplified this timeline a lot, do I need to add only background here?

**Comment by yyx990805** [comment]
@Asya404 yes, background, just to make it reminds the timeline presented on the

note that white background should be only on presentational layer (so in app.vue, not hardcoded in your component itself)

**Review by yyx990805 — APPROVED** [review]
ok, I like it, great job

btw. it works only because of `inheritAttrs` I think, doesn't it?

in the future (next PRs) I will ask to add expanding of entries (https://www.lightningdesignsystem.com/components/activity-timeline/#Multiple-Items-Expanded); for now this PR is great, we can be merging! great work

**Comment by Asya404** [comment]
@yyx990805 thank you! 
I've just added styling directly to the component inside app.js.
sure, in the next PR will add expanded items.

**Pull request merged**
