### PR TITLE
Added accordion component and it's configuration via props

### PR DESCRIPTION
**Pull request by Asya404**
- Added story-accordion component.
- Implemented props to configure accordion content dynamically.

### CODE REVIEW

**Comment by Asya404** [comment]
Passed an array of data to accordion component instead of slots.

**Comment by yyx990805** [comment]
`isOpen` should not be taken from the outside world data (and even worse mutated as it's in toggle function!)

Instead that - consider
```js
const data = defineProp([{label: 'accor1', content: 'txt'}, {...}, {...}])
const opened = ref([false, false, false])
```

**Comment by yyx990805** [comment]
it's not what I expected, however let's move on, it works fine

**Review by yyx990805 — APPROVED** [review]
isOpen should be a new array, contained only within the component

but this will be a subject to a new PR

**Comment by Asya404** [comment]
I thought that isOpen property should be related to each item. If making separate array with only isOpen properties, I would connect it with item by index.

for this branch i made a rebase to main branch and maybe I could merge it already?

**Pull request merged**
